language: python
python:
  - '3.6'
before_install:
  - wget -O firefox-driver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - tar -xzf firefox-driver.tar.gz -C geckodriver
install:
  - 'pip install pipenv'
  - 'pipenv install'
script: 'pipenv run nosetests tasks.py'
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
